apiVersion: v1
kind: Pod
metadata:
  name: simplefile
  labels: 
    app: simple-app
spec:
  containers:
    - name: simple_container
      image: nginx:latest
      ports:
        containerPort: 80
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
    type: LoadBalancer
    selector:
      app: simple-app
    ports:
      - port: 80
        targetPort: 80
        Protocol: TCP


